build:
  prtest:
    image: kkarczmarczyk/node-yarn:6.9
    environment:
      - NPM_CONFIG_USERCONFIG=.npmrc
    commands:
      - export GITHUB_PR_NUMBER=${DRONE_PULL_REQUEST}
      - export GITHUB_REPO=${DRONE_REPO}
      - export APP_NAME=`node -e "console.log(require('./package.json').name);"`
      - yarn
      - yarn config set ${APP_NAME}:lintOptions:outputFormat checkstyle
      - yarn config set ${APP_NAME}:lintOptions:outputFile lint.xml
      - yarn config set ${APP_NAME}:testOptions:outputFormat xunit
      - yarn config set ${APP_NAME}:testOptions:outputFile results.xml
      - "yarn lint ||:"
      - "yarn test ||:"
    when:
      event: pull_request
